title: Máximo Sojo
description: >- # this means to ignore newlines until "baseurl:"
  Desde que empecé mi andadura como desarrollador hace mas de 10 años, he realizado trabajos para agencias, he sido consultor de startups y he colaborado con gente con talento para crear productos digitales tanto para empresas como para consumidores.
  Soy una persona tranquila, curiosa por naturaleza y siempre estoy trabajando para mejorar mis habiliades, un conocimiento a la vez.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: maximosojo
github_username:  maximosojo
facebook_username: 
youtube_username: UCBJiKvFjxK4X_gtEHXajH5Q
instagram_username: maximosojo
linkedin_username: maximosojo

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed